server:
  port: 8081
  servlet: 
    context-path: /rbac
spring:
  application:
    name: demo-rbac
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.6:3306/rbac?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  http:
    encoding:
      charset: utf-8
      enabled: true
      
  thymeleaf:
       cache: false
       mode: LEGACYHTML5
       prefix: classpath:/templates/
       suffix: .html
      
